// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one

insert into accounts (user_id, name, type, currency, starting_balance)
values ($1, $2, $3, $4, $5)
returning id, user_id, name, type, currency, starting_balance, created_at, updated_at
`

type CreateAccountParams struct {
	UserID          uuid.UUID
	Name            string
	Type            string
	Currency        string
	StartingBalance pgtype.Numeric
}

// accounts
func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.Currency,
		arg.StartingBalance,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.StartingBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
delete from accounts where id = $1 and user_id = $2
`

type DeleteAccountParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteAccount(ctx context.Context, arg DeleteAccountParams) error {
	_, err := q.db.Exec(ctx, deleteAccount, arg.ID, arg.UserID)
	return err
}

const getAccount = `-- name: GetAccount :one
select id, user_id, name, type, currency, starting_balance, created_at, updated_at
from accounts where id = $1 and user_id = $2
`

type GetAccountParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetAccount(ctx context.Context, arg GetAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, arg.ID, arg.UserID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.StartingBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccountsByUser = `-- name: ListAccountsByUser :many
select id, user_id, name, type, currency, starting_balance, created_at, updated_at
from accounts where user_id = $1 order by created_at asc
`

func (q *Queries) ListAccountsByUser(ctx context.Context, userID uuid.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.StartingBalance,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
update accounts set
  name = coalesce($1, name),
  type = coalesce($2, type),
  currency = coalesce($3, currency),
  starting_balance = coalesce($4, starting_balance)
where id = $5 and user_id = $6
returning id, user_id, name, type, currency, starting_balance, created_at, updated_at
`

type UpdateAccountParams struct {
	Name            pgtype.Text
	Type            pgtype.Text
	Currency        pgtype.Text
	StartingBalance pgtype.Numeric
	ID              uuid.UUID
	UserID          uuid.UUID
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.Name,
		arg.Type,
		arg.Currency,
		arg.StartingBalance,
		arg.ID,
		arg.UserID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.StartingBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
