// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countHiddenJournals = `-- name: CountHiddenJournals :one
select count(*) from trades where hidden_by_admin = true
`

func (q *Queries) CountHiddenJournals(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countHiddenJournals)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublicTrades = `-- name: CountPublicTrades :one
select count(*) from trades where is_public = true and hidden_by_admin = false
`

func (q *Queries) CountPublicTrades(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPublicTrades)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByStatus = `-- name: CountUsersByStatus :one

select count(*) from profiles where status = $1
`

// admin aggregates (overview cards, signup chart, users-with-counts)
func (q *Queries) CountUsersByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listUsersAdmin = `-- name: ListUsersAdmin :many
select p.id, p.display_name, p.email, p.role, p.status, p.timezone,
  p.avatar_path, p.created_at, p.updated_at,
  (select count(*) from trades t where t.user_id = p.id) as trade_count
from profiles p
where ($1::text = '' or p.display_name ilike '%' || $1::text || '%' or p.email ilike '%' || $1::text || '%')
order by p.created_at desc
limit $3 offset $2
`

type ListUsersAdminParams struct {
	Search     string
	PageOffset int32
	PageLimit  int32
}

type ListUsersAdminRow struct {
	ID          uuid.UUID
	DisplayName pgtype.Text
	Email       pgtype.Text
	Role        string
	Status      string
	Timezone    string
	AvatarPath  pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	TradeCount  int64
}

func (q *Queries) ListUsersAdmin(ctx context.Context, arg ListUsersAdminParams) ([]ListUsersAdminRow, error) {
	rows, err := q.db.Query(ctx, listUsersAdmin, arg.Search, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersAdminRow
	for rows.Next() {
		var i ListUsersAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Email,
			&i.Role,
			&i.Status,
			&i.Timezone,
			&i.AvatarPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TradeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const signupsByDay = `-- name: SignupsByDay :many
select date_trunc('day', created_at)::date as day, count(*) as signups
from profiles
where created_at >= $1::timestamptz
group by 1
order by 1
`

type SignupsByDayRow struct {
	Day     pgtype.Date
	Signups int64
}

func (q *Queries) SignupsByDay(ctx context.Context, since pgtype.Timestamptz) ([]SignupsByDayRow, error) {
	rows, err := q.db.Query(ctx, signupsByDay, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SignupsByDayRow
	for rows.Next() {
		var i SignupsByDayRow
		if err := rows.Scan(&i.Day, &i.Signups); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
