// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Name            string
	Type            string
	Currency        string
	StartingBalance pgtype.Numeric
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type AuditLog struct {
	ID         uuid.UUID
	AdminID    pgtype.UUID
	Action     string
	TargetType string
	TargetID   string
	Meta       []byte
	CreatedAt  pgtype.Timestamptz
}

type Profile struct {
	ID          uuid.UUID
	DisplayName pgtype.Text
	Role        string
	Status      string
	Timezone    string
	AvatarPath  pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Setup struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Name         string
	Rules        pgtype.Text
	Invalidation pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type SiteSetting struct {
	ID              int32
	SiteName        string
	Tagline         pgtype.Text
	LogoPath        pgtype.Text
	FaviconPath     pgtype.Text
	ContactEmail    pgtype.Text
	FooterText      pgtype.Text
	RiskDisclaimer  pgtype.Text
	SocialLinks     []byte
	AllowSignups    bool
	MaintenanceMode bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Tag struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Kind      string
	CreatedAt pgtype.Timestamptz
}

type Trade struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	AccountID     uuid.UUID
	SetupID       pgtype.UUID
	Pair          string
	Direction     string
	Timeframe     pgtype.Text
	OpenedAt      pgtype.Timestamptz
	ClosedAt      pgtype.Timestamptz
	Entry         pgtype.Numeric
	StopLoss      pgtype.Numeric
	TakeProfit    pgtype.Numeric
	ExitPrice     pgtype.Numeric
	LotSize       pgtype.Numeric
	Commission    pgtype.Numeric
	Swap          pgtype.Numeric
	RiskAmount    pgtype.Numeric
	Pnl           pgtype.Numeric
	RMultiple     pgtype.Numeric
	FollowedRules pgtype.Bool
	Emotion       pgtype.Text
	Notes         pgtype.Text
	Status        string
	IsPublic      bool
	HiddenByAdmin bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type TradeImage struct {
	ID        uuid.UUID
	TradeID   uuid.UUID
	PublicID  string
	Kind      pgtype.Text
	Position  int32
	CreatedAt pgtype.Timestamptz
}

type TradeTag struct {
	TradeID uuid.UUID
	TagID   uuid.UUID
}
