// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countNewUsersSince = `-- name: CountNewUsersSince :one
select count(*) from profiles where created_at >= $1
`

func (q *Queries) CountNewUsersSince(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countNewUsersSince, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
select count(*) from profiles
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getProfileByID = `-- name: GetProfileByID :one

select id, display_name, role, status, timezone, avatar_path, created_at, updated_at
from profiles where id = $1
`

// profiles (id = supabase auth uid)
func (q *Queries) GetProfileByID(ctx context.Context, id uuid.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByID, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Role,
		&i.Status,
		&i.Timezone,
		&i.AvatarPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
select id, display_name, role, status, timezone, avatar_path, created_at, updated_at
from profiles
where ($1 = '' or display_name ilike '%' || $1 || '%')
order by created_at desc
limit $2 offset $3
`

type ListUsersParams struct {
	Column1 interface{}
	Limit   int32
	Offset  int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]Profile, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Profile
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Role,
			&i.Status,
			&i.Timezone,
			&i.AvatarPath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfile = `-- name: UpdateProfile :one
update profiles set
  display_name = coalesce($2, display_name),
  timezone = coalesce($3, timezone),
  avatar_path = coalesce($4, avatar_path)
where id = $1
returning id, display_name, role, status, timezone, avatar_path, created_at, updated_at
`

type UpdateProfileParams struct {
	ID          uuid.UUID
	DisplayName pgtype.Text
	Timezone    pgtype.Text
	AvatarPath  pgtype.Text
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, updateProfile,
		arg.ID,
		arg.DisplayName,
		arg.Timezone,
		arg.AvatarPath,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Role,
		&i.Status,
		&i.Timezone,
		&i.AvatarPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProfileStatus = `-- name: UpdateProfileStatus :one
update profiles set status = $2 where id = $1
returning id, display_name, role, status, timezone, avatar_path, created_at, updated_at
`

type UpdateProfileStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateProfileStatus(ctx context.Context, arg UpdateProfileStatusParams) (Profile, error) {
	row := q.db.QueryRow(ctx, updateProfileStatus, arg.ID, arg.Status)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Role,
		&i.Status,
		&i.Timezone,
		&i.AvatarPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
