// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: setups.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSetup = `-- name: CreateSetup :one

insert into setups (user_id, name, rules, invalidation)
values ($1, $2, $3, $4)
returning id, user_id, name, rules, invalidation, created_at, updated_at
`

type CreateSetupParams struct {
	UserID       uuid.UUID
	Name         string
	Rules        pgtype.Text
	Invalidation pgtype.Text
}

// setups
func (q *Queries) CreateSetup(ctx context.Context, arg CreateSetupParams) (Setup, error) {
	row := q.db.QueryRow(ctx, createSetup,
		arg.UserID,
		arg.Name,
		arg.Rules,
		arg.Invalidation,
	)
	var i Setup
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Rules,
		&i.Invalidation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSetup = `-- name: DeleteSetup :exec
delete from setups where id = $1 and user_id = $2
`

type DeleteSetupParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteSetup(ctx context.Context, arg DeleteSetupParams) error {
	_, err := q.db.Exec(ctx, deleteSetup, arg.ID, arg.UserID)
	return err
}

const getSetup = `-- name: GetSetup :one
select id, user_id, name, rules, invalidation, created_at, updated_at
from setups where id = $1 and user_id = $2
`

type GetSetupParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetSetup(ctx context.Context, arg GetSetupParams) (Setup, error) {
	row := q.db.QueryRow(ctx, getSetup, arg.ID, arg.UserID)
	var i Setup
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Rules,
		&i.Invalidation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSetupsByUser = `-- name: ListSetupsByUser :many
select id, user_id, name, rules, invalidation, created_at, updated_at
from setups where user_id = $1 order by name asc
`

func (q *Queries) ListSetupsByUser(ctx context.Context, userID uuid.UUID) ([]Setup, error) {
	rows, err := q.db.Query(ctx, listSetupsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Setup
	for rows.Next() {
		var i Setup
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Rules,
			&i.Invalidation,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSetup = `-- name: UpdateSetup :one
update setups set
  name = coalesce($1, name),
  rules = coalesce($2, rules),
  invalidation = coalesce($3, invalidation)
where id = $4 and user_id = $5
returning id, user_id, name, rules, invalidation, created_at, updated_at
`

type UpdateSetupParams struct {
	Name         pgtype.Text
	Rules        pgtype.Text
	Invalidation pgtype.Text
	ID           uuid.UUID
	UserID       uuid.UUID
}

func (q *Queries) UpdateSetup(ctx context.Context, arg UpdateSetupParams) (Setup, error) {
	row := q.db.QueryRow(ctx, updateSetup,
		arg.Name,
		arg.Rules,
		arg.Invalidation,
		arg.ID,
		arg.UserID,
	)
	var i Setup
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Rules,
		&i.Invalidation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
