// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: site_settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSiteSettings = `-- name: GetSiteSettings :one

select id, site_name, tagline, logo_path, favicon_path, contact_email, footer_text, risk_disclaimer, social_links, allow_signups, maintenance_mode, created_at, updated_at from site_settings where id = 1
`

// site_settings (single row id = 1)
func (q *Queries) GetSiteSettings(ctx context.Context) (SiteSetting, error) {
	row := q.db.QueryRow(ctx, getSiteSettings)
	var i SiteSetting
	err := row.Scan(
		&i.ID,
		&i.SiteName,
		&i.Tagline,
		&i.LogoPath,
		&i.FaviconPath,
		&i.ContactEmail,
		&i.FooterText,
		&i.RiskDisclaimer,
		&i.SocialLinks,
		&i.AllowSignups,
		&i.MaintenanceMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSiteSettings = `-- name: UpdateSiteSettings :one
update site_settings set
  site_name = coalesce($1, site_name),
  tagline = coalesce($2, tagline),
  logo_path = coalesce($3, logo_path),
  favicon_path = coalesce($4, favicon_path),
  contact_email = coalesce($5, contact_email),
  footer_text = coalesce($6, footer_text),
  risk_disclaimer = coalesce($7, risk_disclaimer),
  social_links = coalesce($8, social_links),
  allow_signups = coalesce($9, allow_signups),
  maintenance_mode = coalesce($10, maintenance_mode)
where id = 1
returning id, site_name, tagline, logo_path, favicon_path, contact_email, footer_text, risk_disclaimer, social_links, allow_signups, maintenance_mode, created_at, updated_at
`

type UpdateSiteSettingsParams struct {
	SiteName        pgtype.Text
	Tagline         pgtype.Text
	LogoPath        pgtype.Text
	FaviconPath     pgtype.Text
	ContactEmail    pgtype.Text
	FooterText      pgtype.Text
	RiskDisclaimer  pgtype.Text
	SocialLinks     []byte
	AllowSignups    pgtype.Bool
	MaintenanceMode pgtype.Bool
}

func (q *Queries) UpdateSiteSettings(ctx context.Context, arg UpdateSiteSettingsParams) (SiteSetting, error) {
	row := q.db.QueryRow(ctx, updateSiteSettings,
		arg.SiteName,
		arg.Tagline,
		arg.LogoPath,
		arg.FaviconPath,
		arg.ContactEmail,
		arg.FooterText,
		arg.RiskDisclaimer,
		arg.SocialLinks,
		arg.AllowSignups,
		arg.MaintenanceMode,
	)
	var i SiteSetting
	err := row.Scan(
		&i.ID,
		&i.SiteName,
		&i.Tagline,
		&i.LogoPath,
		&i.FaviconPath,
		&i.ContactEmail,
		&i.FooterText,
		&i.RiskDisclaimer,
		&i.SocialLinks,
		&i.AllowSignups,
		&i.MaintenanceMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
