// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const statsByPair = `-- name: StatsByPair :many
select pair, count(*) as trades, sum(pnl) as total_pnl, avg(r_multiple) as avg_r
from trades where user_id = $1 and status = 'closed'
  and ($2::uuid is null or account_id = $2)
group by pair
`

type StatsByPairParams struct {
	UserID  uuid.UUID
	Column2 uuid.UUID
}

type StatsByPairRow struct {
	Pair     string
	Trades   int64
	TotalPnl int64
	AvgR     float64
}

func (q *Queries) StatsByPair(ctx context.Context, arg StatsByPairParams) ([]StatsByPairRow, error) {
	rows, err := q.db.Query(ctx, statsByPair, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsByPairRow
	for rows.Next() {
		var i StatsByPairRow
		if err := rows.Scan(
			&i.Pair,
			&i.Trades,
			&i.TotalPnl,
			&i.AvgR,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsBySetup = `-- name: StatsBySetup :many
select setup_id, count(*) as trades, sum(pnl) as total_pnl, avg(r_multiple) as avg_r
from trades where user_id = $1 and status = 'closed'
  and ($2::uuid is null or account_id = $2)
group by setup_id
`

type StatsBySetupParams struct {
	UserID  uuid.UUID
	Column2 uuid.UUID
}

type StatsBySetupRow struct {
	SetupID  pgtype.UUID
	Trades   int64
	TotalPnl int64
	AvgR     float64
}

func (q *Queries) StatsBySetup(ctx context.Context, arg StatsBySetupParams) ([]StatsBySetupRow, error) {
	rows, err := q.db.Query(ctx, statsBySetup, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsBySetupRow
	for rows.Next() {
		var i StatsBySetupRow
		if err := rows.Scan(
			&i.SetupID,
			&i.Trades,
			&i.TotalPnl,
			&i.AvgR,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsClosedTrades = `-- name: StatsClosedTrades :many

select id, pnl, r_multiple, followed_rules, opened_at, closed_at, pair, setup_id, account_id
from trades
where user_id = $1 and status = 'closed'
  and ($2::uuid is null or account_id = $2)
order by closed_at asc nulls last
`

type StatsClosedTradesParams struct {
	UserID  uuid.UUID
	Column2 uuid.UUID
}

type StatsClosedTradesRow struct {
	ID            uuid.UUID
	Pnl           pgtype.Numeric
	RMultiple     pgtype.Numeric
	FollowedRules pgtype.Bool
	OpenedAt      pgtype.Timestamptz
	ClosedAt      pgtype.Timestamptz
	Pair          string
	SetupID       pgtype.UUID
	AccountID     uuid.UUID
}

// stats: raw aggregates; R/win-rate/expectancy/drawdown math lives in pkg/calc (unit tested)
func (q *Queries) StatsClosedTrades(ctx context.Context, arg StatsClosedTradesParams) ([]StatsClosedTradesRow, error) {
	rows, err := q.db.Query(ctx, statsClosedTrades, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsClosedTradesRow
	for rows.Next() {
		var i StatsClosedTradesRow
		if err := rows.Scan(
			&i.ID,
			&i.Pnl,
			&i.RMultiple,
			&i.FollowedRules,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.Pair,
			&i.SetupID,
			&i.AccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsEquityCurve = `-- name: StatsEquityCurve :many
select closed_at, pnl from trades
where user_id = $1 and status = 'closed'
  and ($2::uuid is null or account_id = $2)
order by closed_at asc nulls last
`

type StatsEquityCurveParams struct {
	UserID  uuid.UUID
	Column2 uuid.UUID
}

type StatsEquityCurveRow struct {
	ClosedAt pgtype.Timestamptz
	Pnl      pgtype.Numeric
}

func (q *Queries) StatsEquityCurve(ctx context.Context, arg StatsEquityCurveParams) ([]StatsEquityCurveRow, error) {
	rows, err := q.db.Query(ctx, statsEquityCurve, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsEquityCurveRow
	for rows.Next() {
		var i StatsEquityCurveRow
		if err := rows.Scan(&i.ClosedAt, &i.Pnl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
