// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTag = `-- name: CreateTag :one

insert into tags (user_id, name, kind)
values ($1, $2, $3)
returning id, user_id, name, kind, created_at
`

type CreateTagParams struct {
	UserID uuid.UUID
	Name   string
	Kind   string
}

// tags
func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.UserID, arg.Name, arg.Kind)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
delete from tags where id = $1 and user_id = $2
`

type DeleteTagParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) error {
	_, err := q.db.Exec(ctx, deleteTag, arg.ID, arg.UserID)
	return err
}

const getTag = `-- name: GetTag :one
select id, user_id, name, kind, created_at
from tags where id = $1 and user_id = $2
`

type GetTagParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetTag(ctx context.Context, arg GetTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, getTag, arg.ID, arg.UserID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}

const listTagsByUser = `-- name: ListTagsByUser :many
select id, user_id, name, kind, created_at
from tags where user_id = $1 order by name asc
`

func (q *Queries) ListTagsByUser(ctx context.Context, userID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Kind,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTag = `-- name: UpdateTag :one
update tags set
  name = coalesce($1, name),
  kind = coalesce($2, kind)
where id = $3 and user_id = $4
returning id, user_id, name, kind, created_at
`

type UpdateTagParams struct {
	Name   pgtype.Text
	Kind   pgtype.Text
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, updateTag,
		arg.Name,
		arg.Kind,
		arg.ID,
		arg.UserID,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}
