// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trades.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAllTrades = `-- name: CountAllTrades :one
select count(*) from trades
`

func (q *Queries) CountAllTrades(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllTrades)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTrades = `-- name: CountTrades :one
select count(*) from trades where user_id = $1
`

func (q *Queries) CountTrades(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTrades, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTrade = `-- name: CreateTrade :one

insert into trades (
  user_id, account_id, setup_id, pair, direction, timeframe,
  opened_at, closed_at, entry, stop_loss, take_profit, exit_price,
  lot_size, commission, swap, risk_amount, pnl, r_multiple,
  followed_rules, emotion, notes, status, is_public
) values (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12,
  $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23
) returning id, user_id, account_id, setup_id, pair, direction, timeframe, opened_at, closed_at, entry, stop_loss, take_profit, exit_price, lot_size, commission, swap, risk_amount, pnl, r_multiple, followed_rules, emotion, notes, status, is_public, hidden_by_admin, created_at, updated_at
`

type CreateTradeParams struct {
	UserID        uuid.UUID
	AccountID     uuid.UUID
	SetupID       pgtype.UUID
	Pair          string
	Direction     string
	Timeframe     pgtype.Text
	OpenedAt      pgtype.Timestamptz
	ClosedAt      pgtype.Timestamptz
	Entry         pgtype.Numeric
	StopLoss      pgtype.Numeric
	TakeProfit    pgtype.Numeric
	ExitPrice     pgtype.Numeric
	LotSize       pgtype.Numeric
	Commission    pgtype.Numeric
	Swap          pgtype.Numeric
	RiskAmount    pgtype.Numeric
	Pnl           pgtype.Numeric
	RMultiple     pgtype.Numeric
	FollowedRules pgtype.Bool
	Emotion       pgtype.Text
	Notes         pgtype.Text
	Status        string
	IsPublic      bool
}

// trades
func (q *Queries) CreateTrade(ctx context.Context, arg CreateTradeParams) (Trade, error) {
	row := q.db.QueryRow(ctx, createTrade,
		arg.UserID,
		arg.AccountID,
		arg.SetupID,
		arg.Pair,
		arg.Direction,
		arg.Timeframe,
		arg.OpenedAt,
		arg.ClosedAt,
		arg.Entry,
		arg.StopLoss,
		arg.TakeProfit,
		arg.ExitPrice,
		arg.LotSize,
		arg.Commission,
		arg.Swap,
		arg.RiskAmount,
		arg.Pnl,
		arg.RMultiple,
		arg.FollowedRules,
		arg.Emotion,
		arg.Notes,
		arg.Status,
		arg.IsPublic,
	)
	var i Trade
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.SetupID,
		&i.Pair,
		&i.Direction,
		&i.Timeframe,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.Entry,
		&i.StopLoss,
		&i.TakeProfit,
		&i.ExitPrice,
		&i.LotSize,
		&i.Commission,
		&i.Swap,
		&i.RiskAmount,
		&i.Pnl,
		&i.RMultiple,
		&i.FollowedRules,
		&i.Emotion,
		&i.Notes,
		&i.Status,
		&i.IsPublic,
		&i.HiddenByAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTrade = `-- name: DeleteTrade :exec
delete from trades where id = $1 and user_id = $2
`

type DeleteTradeParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteTrade(ctx context.Context, arg DeleteTradeParams) error {
	_, err := q.db.Exec(ctx, deleteTrade, arg.ID, arg.UserID)
	return err
}

const exportTradesByUser = `-- name: ExportTradesByUser :many
select id, user_id, account_id, setup_id, pair, direction, timeframe, opened_at, closed_at, entry, stop_loss, take_profit, exit_price, lot_size, commission, swap, risk_amount, pnl, r_multiple, followed_rules, emotion, notes, status, is_public, hidden_by_admin, created_at, updated_at from trades where user_id = $1 order by opened_at asc nulls last
`

func (q *Queries) ExportTradesByUser(ctx context.Context, userID uuid.UUID) ([]Trade, error) {
	rows, err := q.db.Query(ctx, exportTradesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trade
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.SetupID,
			&i.Pair,
			&i.Direction,
			&i.Timeframe,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.Entry,
			&i.StopLoss,
			&i.TakeProfit,
			&i.ExitPrice,
			&i.LotSize,
			&i.Commission,
			&i.Swap,
			&i.RiskAmount,
			&i.Pnl,
			&i.RMultiple,
			&i.FollowedRules,
			&i.Emotion,
			&i.Notes,
			&i.Status,
			&i.IsPublic,
			&i.HiddenByAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrade = `-- name: GetTrade :one
select id, user_id, account_id, setup_id, pair, direction, timeframe, opened_at, closed_at, entry, stop_loss, take_profit, exit_price, lot_size, commission, swap, risk_amount, pnl, r_multiple, followed_rules, emotion, notes, status, is_public, hidden_by_admin, created_at, updated_at from trades where id = $1 and user_id = $2
`

type GetTradeParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetTrade(ctx context.Context, arg GetTradeParams) (Trade, error) {
	row := q.db.QueryRow(ctx, getTrade, arg.ID, arg.UserID)
	var i Trade
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.SetupID,
		&i.Pair,
		&i.Direction,
		&i.Timeframe,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.Entry,
		&i.StopLoss,
		&i.TakeProfit,
		&i.ExitPrice,
		&i.LotSize,
		&i.Commission,
		&i.Swap,
		&i.RiskAmount,
		&i.Pnl,
		&i.RMultiple,
		&i.FollowedRules,
		&i.Emotion,
		&i.Notes,
		&i.Status,
		&i.IsPublic,
		&i.HiddenByAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hideJournal = `-- name: HideJournal :one
update trades set hidden_by_admin = $2 where id = $1
returning id, user_id, account_id, setup_id, pair, direction, timeframe, opened_at, closed_at, entry, stop_loss, take_profit, exit_price, lot_size, commission, swap, risk_amount, pnl, r_multiple, followed_rules, emotion, notes, status, is_public, hidden_by_admin, created_at, updated_at
`

type HideJournalParams struct {
	ID            uuid.UUID
	HiddenByAdmin bool
}

func (q *Queries) HideJournal(ctx context.Context, arg HideJournalParams) (Trade, error) {
	row := q.db.QueryRow(ctx, hideJournal, arg.ID, arg.HiddenByAdmin)
	var i Trade
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.SetupID,
		&i.Pair,
		&i.Direction,
		&i.Timeframe,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.Entry,
		&i.StopLoss,
		&i.TakeProfit,
		&i.ExitPrice,
		&i.LotSize,
		&i.Commission,
		&i.Swap,
		&i.RiskAmount,
		&i.Pnl,
		&i.RMultiple,
		&i.FollowedRules,
		&i.Emotion,
		&i.Notes,
		&i.Status,
		&i.IsPublic,
		&i.HiddenByAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublicJournals = `-- name: ListPublicJournals :many
select t.id, t.user_id, t.account_id, t.setup_id, t.pair, t.direction, t.timeframe, t.opened_at, t.closed_at, t.entry, t.stop_loss, t.take_profit, t.exit_price, t.lot_size, t.commission, t.swap, t.risk_amount, t.pnl, t.r_multiple, t.followed_rules, t.emotion, t.notes, t.status, t.is_public, t.hidden_by_admin, t.created_at, t.updated_at, p.display_name, s.name as setup_name
from trades t
join profiles p on p.id = t.user_id
left join setups s on s.id = t.setup_id
where t.is_public = true and t.hidden_by_admin = false
order by t.created_at desc
limit $1 offset $2
`

type ListPublicJournalsParams struct {
	Limit  int32
	Offset int32
}

type ListPublicJournalsRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	AccountID     uuid.UUID
	SetupID       pgtype.UUID
	Pair          string
	Direction     string
	Timeframe     pgtype.Text
	OpenedAt      pgtype.Timestamptz
	ClosedAt      pgtype.Timestamptz
	Entry         pgtype.Numeric
	StopLoss      pgtype.Numeric
	TakeProfit    pgtype.Numeric
	ExitPrice     pgtype.Numeric
	LotSize       pgtype.Numeric
	Commission    pgtype.Numeric
	Swap          pgtype.Numeric
	RiskAmount    pgtype.Numeric
	Pnl           pgtype.Numeric
	RMultiple     pgtype.Numeric
	FollowedRules pgtype.Bool
	Emotion       pgtype.Text
	Notes         pgtype.Text
	Status        string
	IsPublic      bool
	HiddenByAdmin bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DisplayName   pgtype.Text
	SetupName     pgtype.Text
}

func (q *Queries) ListPublicJournals(ctx context.Context, arg ListPublicJournalsParams) ([]ListPublicJournalsRow, error) {
	rows, err := q.db.Query(ctx, listPublicJournals, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicJournalsRow
	for rows.Next() {
		var i ListPublicJournalsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.SetupID,
			&i.Pair,
			&i.Direction,
			&i.Timeframe,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.Entry,
			&i.StopLoss,
			&i.TakeProfit,
			&i.ExitPrice,
			&i.LotSize,
			&i.Commission,
			&i.Swap,
			&i.RiskAmount,
			&i.Pnl,
			&i.RMultiple,
			&i.FollowedRules,
			&i.Emotion,
			&i.Notes,
			&i.Status,
			&i.IsPublic,
			&i.HiddenByAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisplayName,
			&i.SetupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrades = `-- name: ListTrades :many
select id, user_id, account_id, setup_id, pair, direction, timeframe, opened_at, closed_at, entry, stop_loss, take_profit, exit_price, lot_size, commission, swap, risk_amount, pnl, r_multiple, followed_rules, emotion, notes, status, is_public, hidden_by_admin, created_at, updated_at from trades
where user_id = $1
  and ($2 = '' or pair = $2)
  and ($3::uuid is null or setup_id = $3)
  and ($4 = '' or status = $4)
  and ($5::uuid is null or account_id = $5)
  and ($6 = '' or direction = $6)
  and ($7::timestamptz is null or opened_at >= $7)
  and ($8::timestamptz is null or opened_at <= $8)
order by opened_at desc nulls last, created_at desc
limit $9 offset $10
`

type ListTradesParams struct {
	UserID  uuid.UUID
	Column2 interface{}
	Column3 uuid.UUID
	Column4 interface{}
	Column5 uuid.UUID
	Column6 interface{}
	Column7 pgtype.Timestamptz
	Column8 pgtype.Timestamptz
	Limit   int32
	Offset  int32
}

func (q *Queries) ListTrades(ctx context.Context, arg ListTradesParams) ([]Trade, error) {
	rows, err := q.db.Query(ctx, listTrades,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trade
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.SetupID,
			&i.Pair,
			&i.Direction,
			&i.Timeframe,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.Entry,
			&i.StopLoss,
			&i.TakeProfit,
			&i.ExitPrice,
			&i.LotSize,
			&i.Commission,
			&i.Swap,
			&i.RiskAmount,
			&i.Pnl,
			&i.RMultiple,
			&i.FollowedRules,
			&i.Emotion,
			&i.Notes,
			&i.Status,
			&i.IsPublic,
			&i.HiddenByAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTrade = `-- name: UpdateTrade :one
update trades set
  account_id = coalesce($1, account_id),
  setup_id = coalesce($2, setup_id),
  pair = coalesce($3, pair),
  direction = coalesce($4, direction),
  timeframe = coalesce($5, timeframe),
  opened_at = coalesce($6, opened_at),
  closed_at = coalesce($7, closed_at),
  entry = coalesce($8, entry),
  stop_loss = coalesce($9, stop_loss),
  take_profit = coalesce($10, take_profit),
  exit_price = coalesce($11, exit_price),
  lot_size = coalesce($12, lot_size),
  commission = coalesce($13, commission),
  swap = coalesce($14, swap),
  risk_amount = coalesce($15, risk_amount),
  pnl = coalesce($16, pnl),
  r_multiple = coalesce($17, r_multiple),
  followed_rules = coalesce($18, followed_rules),
  emotion = coalesce($19, emotion),
  notes = coalesce($20, notes),
  status = coalesce($21, status)
where id = $22 and user_id = $23
returning id, user_id, account_id, setup_id, pair, direction, timeframe, opened_at, closed_at, entry, stop_loss, take_profit, exit_price, lot_size, commission, swap, risk_amount, pnl, r_multiple, followed_rules, emotion, notes, status, is_public, hidden_by_admin, created_at, updated_at
`

type UpdateTradeParams struct {
	AccountID     pgtype.UUID
	SetupID       pgtype.UUID
	Pair          pgtype.Text
	Direction     pgtype.Text
	Timeframe     pgtype.Text
	OpenedAt      pgtype.Timestamptz
	ClosedAt      pgtype.Timestamptz
	Entry         pgtype.Numeric
	StopLoss      pgtype.Numeric
	TakeProfit    pgtype.Numeric
	ExitPrice     pgtype.Numeric
	LotSize       pgtype.Numeric
	Commission    pgtype.Numeric
	Swap          pgtype.Numeric
	RiskAmount    pgtype.Numeric
	Pnl           pgtype.Numeric
	RMultiple     pgtype.Numeric
	FollowedRules pgtype.Bool
	Emotion       pgtype.Text
	Notes         pgtype.Text
	Status        pgtype.Text
	ID            uuid.UUID
	UserID        uuid.UUID
}

func (q *Queries) UpdateTrade(ctx context.Context, arg UpdateTradeParams) (Trade, error) {
	row := q.db.QueryRow(ctx, updateTrade,
		arg.AccountID,
		arg.SetupID,
		arg.Pair,
		arg.Direction,
		arg.Timeframe,
		arg.OpenedAt,
		arg.ClosedAt,
		arg.Entry,
		arg.StopLoss,
		arg.TakeProfit,
		arg.ExitPrice,
		arg.LotSize,
		arg.Commission,
		arg.Swap,
		arg.RiskAmount,
		arg.Pnl,
		arg.RMultiple,
		arg.FollowedRules,
		arg.Emotion,
		arg.Notes,
		arg.Status,
		arg.ID,
		arg.UserID,
	)
	var i Trade
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.SetupID,
		&i.Pair,
		&i.Direction,
		&i.Timeframe,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.Entry,
		&i.StopLoss,
		&i.TakeProfit,
		&i.ExitPrice,
		&i.LotSize,
		&i.Commission,
		&i.Swap,
		&i.RiskAmount,
		&i.Pnl,
		&i.RMultiple,
		&i.FollowedRules,
		&i.Emotion,
		&i.Notes,
		&i.Status,
		&i.IsPublic,
		&i.HiddenByAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTradeVisibility = `-- name: UpdateTradeVisibility :one
update trades set is_public = $3 where id = $1 and user_id = $2
returning id, user_id, account_id, setup_id, pair, direction, timeframe, opened_at, closed_at, entry, stop_loss, take_profit, exit_price, lot_size, commission, swap, risk_amount, pnl, r_multiple, followed_rules, emotion, notes, status, is_public, hidden_by_admin, created_at, updated_at
`

type UpdateTradeVisibilityParams struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	IsPublic bool
}

func (q *Queries) UpdateTradeVisibility(ctx context.Context, arg UpdateTradeVisibilityParams) (Trade, error) {
	row := q.db.QueryRow(ctx, updateTradeVisibility, arg.ID, arg.UserID, arg.IsPublic)
	var i Trade
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.SetupID,
		&i.Pair,
		&i.Direction,
		&i.Timeframe,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.Entry,
		&i.StopLoss,
		&i.TakeProfit,
		&i.ExitPrice,
		&i.LotSize,
		&i.Commission,
		&i.Swap,
		&i.RiskAmount,
		&i.Pnl,
		&i.RMultiple,
		&i.FollowedRules,
		&i.Emotion,
		&i.Notes,
		&i.Status,
		&i.IsPublic,
		&i.HiddenByAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
