// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trade_images.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countImagesByTrade = `-- name: CountImagesByTrade :one
select count(*) from trade_images where trade_id = $1
`

func (q *Queries) CountImagesByTrade(ctx context.Context, tradeID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countImagesByTrade, tradeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTradeImage = `-- name: CreateTradeImage :one

insert into trade_images (trade_id, public_id, kind, position)
values ($1, $2, $3, $4)
returning id, trade_id, public_id, kind, position, created_at
`

type CreateTradeImageParams struct {
	TradeID  uuid.UUID
	PublicID string
	Kind     pgtype.Text
	Position int32
}

// trade_images (only Cloudinary public_id is stored)
func (q *Queries) CreateTradeImage(ctx context.Context, arg CreateTradeImageParams) (TradeImage, error) {
	row := q.db.QueryRow(ctx, createTradeImage,
		arg.TradeID,
		arg.PublicID,
		arg.Kind,
		arg.Position,
	)
	var i TradeImage
	err := row.Scan(
		&i.ID,
		&i.TradeID,
		&i.PublicID,
		&i.Kind,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTradeImage = `-- name: DeleteTradeImage :exec
delete from trade_images where id = $1
`

func (q *Queries) DeleteTradeImage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTradeImage, id)
	return err
}

const getTradeImage = `-- name: GetTradeImage :one
select id, trade_id, public_id, kind, position, created_at
from trade_images where id = $1
`

func (q *Queries) GetTradeImage(ctx context.Context, id uuid.UUID) (TradeImage, error) {
	row := q.db.QueryRow(ctx, getTradeImage, id)
	var i TradeImage
	err := row.Scan(
		&i.ID,
		&i.TradeID,
		&i.PublicID,
		&i.Kind,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const listImagesByTrade = `-- name: ListImagesByTrade :many
select id, trade_id, public_id, kind, position, created_at
from trade_images where trade_id = $1 order by position asc
`

func (q *Queries) ListImagesByTrade(ctx context.Context, tradeID uuid.UUID) ([]TradeImage, error) {
	rows, err := q.db.Query(ctx, listImagesByTrade, tradeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TradeImage
	for rows.Next() {
		var i TradeImage
		if err := rows.Scan(
			&i.ID,
			&i.TradeID,
			&i.PublicID,
			&i.Kind,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
