// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trade_tags.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addTradeTag = `-- name: AddTradeTag :exec

insert into trade_tags (trade_id, tag_id) values ($1, $2)
on conflict do nothing
`

type AddTradeTagParams struct {
	TradeID uuid.UUID
	TagID   uuid.UUID
}

// trade_tags
func (q *Queries) AddTradeTag(ctx context.Context, arg AddTradeTagParams) error {
	_, err := q.db.Exec(ctx, addTradeTag, arg.TradeID, arg.TagID)
	return err
}

const clearTradeTags = `-- name: ClearTradeTags :exec
delete from trade_tags where trade_id = $1
`

func (q *Queries) ClearTradeTags(ctx context.Context, tradeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearTradeTags, tradeID)
	return err
}

const listTagsByTrade = `-- name: ListTagsByTrade :many
select g.id, g.user_id, g.name, g.kind, g.created_at
from tags g join trade_tags tt on tt.tag_id = g.id
where tt.trade_id = $1 order by g.name asc
`

func (q *Queries) ListTagsByTrade(ctx context.Context, tradeID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsByTrade, tradeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Kind,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTradeTag = `-- name: RemoveTradeTag :exec
delete from trade_tags where trade_id = $1 and tag_id = $2
`

type RemoveTradeTagParams struct {
	TradeID uuid.UUID
	TagID   uuid.UUID
}

func (q *Queries) RemoveTradeTag(ctx context.Context, arg RemoveTradeTagParams) error {
	_, err := q.db.Exec(ctx, removeTradeTag, arg.TradeID, arg.TagID)
	return err
}
